sample/src/main/resources/events/SNMP_Link_UpDown.xml
sample/src/main/resources/events/sample.xml
sample/src/main/resources/syslog/Cisco.syslog.xml
sample/src/test/java/org/opennms/integration/api/sample/MyEventConfExtensionTest.java
sample/src/test/java/org/opennms/integration/api/sample/MySyslogMatchExtensionTest.java
xml/src/main/java/org/opennms/integration/api/xml/ClasspathEventDefinitionLoader.java
xml/src/main/java/org/opennms/integration/api/xml/ClasspathSyslogMatchLoader.java
xml/src/main/java/org/opennms/integration/api/xml/schema/eventconf/Event.java
xml/src/main/java/org/opennms/integration/api/xml/schema/syslog/UeiMatch.java
xml/src/main/xsds/eventconf.xsd
xml/src/main/xsds/syslog.xsd

This PR adds Priority to the Event and UeiMatch objects and the matching schemas.

HZN-1419: Wire support for Priority in EventDefinition and UeiMatch

---

api/pom.xml
api/src/main/java/org/opennms/integration/api/v1/dao/AlarmFeedbackDao.java
api/src/main/java/org/opennms/integration/api/v1/feedback/AlarmFeedbackListener.java
api/src/main/java/org/opennms/integration/api/v1/model/AlarmFeedback.java
common/pom.xml
karaf-features/pom.xml
pom.xml
sample/pom.xml
sample/src/main/java/org/opennms/integration/api/sample/MyAlarmFeedbackListener.java
sample/src/main/java/org/opennms/integration/api/sample/SampleAlarmManager.java
sample/src/main/resources/OSGI-INF/blueprint/blueprint.xml
test-api/pom.xml
xml/pom.xml

This PR adds alarm feedback support to the integration API.

HZN-1433: Update integration api to handle alarm feedback without Kafka

---

common/src/main/java/org/opennms/integration/api/v1/model/immutables/ImmutableTopologyPort.java

Trivial change to allow ifIndex on a port to be set null.
Jira: https://issues.opennms.org/browse/OCE-55

OCE-55: Minor change to port impl to allow ifIndex to be set null

---

api/src/main/java/org/opennms/integration/api/v1/model/AlarmFeedback.java
api/src/main/java/org/opennms/integration/api/v1/model/DatabaseEvent.java
common/src/main/java/org/opennms/integration/api/v1/model/immutables/ImmutableAlarmFeedback.java
common/src/main/java/org/opennms/integration/api/v1/model/immutables/ImmutableDatabaseEvent.java

This PR adds two Model implementations to the integration API that previously only existed in the OpenNMS project.
I have changes ready for OpenNMS to switch to using these implementations.
Jira: https://issues.opennms.org/browse/OIA-17

OIA-17: Move implementations for API types from Opennms to integration API

---

api/pom.xml
api/src/main/java/org/opennms/integration/api/v1/ticketing/TicketingPlugin.java
common/pom.xml
config/pom.xml
karaf-features/pom.xml
pom.xml
sample/pom.xml
sample/src/main/java/org/opennms/integration/api/sample/SampleDetector.java
sample/src/main/java/org/opennms/integration/api/sample/SampleTicketerPlugin.java
test-api/pom.xml

https://issues.opennms.org/browse/OIA-19

OIA-19: Fix Ticketing API to return Ticket Id

---

api/src/main/java/org/opennms/integration/api/v1/timeseries/Aggregation.java
api/src/main/java/org/opennms/integration/api/v1/timeseries/Metric.java
api/src/main/java/org/opennms/integration/api/v1/timeseries/Sample.java
api/src/main/java/org/opennms/integration/api/v1/timeseries/StorageException.java
api/src/main/java/org/opennms/integration/api/v1/timeseries/Tag.java
api/src/main/java/org/opennms/integration/api/v1/timeseries/TimeSeriesFetchRequest.java
api/src/main/java/org/opennms/integration/api/v1/timeseries/TimeSeriesStorage.java
api/src/main/java/org/opennms/integration/api/v1/timeseries/package-info.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableMetric.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableSample.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableTag.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableTimeSeriesFetchRequest.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/MetricValidator.java
common/src/main/java/org/opennms/integration/api/v1/util/ImmutableCollections.java
common/src/test/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableMetricTest.java

The timeseries integration layer classes
Jira: https://issues.opennms.org/browse/NMS-12383

NMS-12383 add timeseries integration layer classes

---

common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableMetric.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableTag.java
common/src/test/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableMetricTest.java

This PR fixes the toString method on the CommonTag class and the ImmutableMetricBuilder, add test
* Jira: https://issues.opennms.org/browse/NMS-12383

NMS-12383: fix problem with ImmutableMetricBuilder

---

api/src/main/java/org/opennms/integration/api/v1/timeseries/Metric.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableMetric.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/MetricValidator.java
common/src/test/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableMetricTest.java

This PR removes the former mandatory tags mtype and unit

NMS-12383 Timeseries, remove mandatory tags

---

api/src/main/java/org/opennms/integration/api/v1/graph/Properties.java
common/src/main/java/org/opennms/integration/api/v1/graph/immutables/ImmutableEdge.java
common/src/main/java/org/opennms/integration/api/v1/graph/immutables/ImmutableGraph.java
common/src/main/java/org/opennms/integration/api/v1/graph/immutables/ImmutableGraphContainer.java
common/src/main/java/org/opennms/integration/api/v1/graph/immutables/ImmutableGraphContainerInfo.java
common/src/main/java/org/opennms/integration/api/v1/graph/immutables/ImmutableGraphInfo.java
common/src/main/java/org/opennms/integration/api/v1/graph/immutables/ImmutableNodeRef.java
common/src/main/java/org/opennms/integration/api/v1/graph/immutables/ImmutableVertex.java
common/src/main/java/org/opennms/integration/api/v1/graph/immutables/ImmutableVertexRef.java
common/src/main/java/org/opennms/integration/api/v1/graph/status/immutables/StatusInfoImmutable.java

While implementing ALEC-84, I will suggest changes for the integration API in this pull request.

WIP: ALEC-84: Polish graph api while implementing Alec graph plugin

---

api/src/main/java/org/opennms/integration/api/v1/timeseries/IntrinsicTagNames.java
api/src/main/java/org/opennms/integration/api/v1/timeseries/MetaTagNames.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableMetric.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableTag.java

This PR splits the predefined tag names into Intrinsic and Meta Tag names.
Jira: https://issues.opennms.org/browse/NMS-12771

NMS-12771: Evaluate and improve opennms-cortex-tss-plugin: split intrinsic and meta tag names

---

README.md
pom.xml
test-suites/pom.xml
test-suites/tss-tests/README.md
test-suites/tss-tests/pom.xml
test-suites/tss-tests/src/main/java/org/opennms/integration/api/v1/timeseries/AbstractStorageIntegrationTest.java
test-suites/tss-tests/src/test/java/org/opennms/integration/api/v1/timeseries/InMemoryStorage.java
test-suites/tss-tests/src/test/java/org/opennms/integration/api/v1/timeseries/InMemoryStorageTest.java

Jira: https://issues.opennms.org/browse/NMS-12796

NMS-12796: Move integration tests to OIA

---

api/src/main/java/org/opennms/integration/api/v1/model/Alarm.java
api/src/main/java/org/opennms/integration/api/v1/model/Node.java
common/src/main/java/org/opennms/integration/api/v1/model/immutables/ImmutableAlarm.java
common/src/main/java/org/opennms/integration/api/v1/model/immutables/ImmutableNode.java

These were found to be useful for new plugins & extensions.

Add some additional properties to the alarm & node objects.

---

README.md
api/src/main/java/org/opennms/integration/api/v1/timeseries/README.md

Jira: https://issues.opennms.org/browse/NMS-12911

NMS-12911: Create howto for writing tss plugins

---

api/src/main/java/org/opennms/integration/api/v1/timeseries/TagMatcher.java
api/src/main/java/org/opennms/integration/api/v1/timeseries/TimeSeriesStorage.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableTagMatcher.java
test-suites/tss-tests/src/main/java/org/opennms/integration/api/v1/timeseries/AbstractStorageIntegrationTest.java
test-suites/tss-tests/src/main/java/org/opennms/integration/api/v1/timeseries/InMemoryStorage.java

https://issues.opennms.org/browse/NMS-13357

NMS-13357: Lever regex for indexing of resource paths (resorceId)

---

test-suites/tss-tests/src/main/java/org/opennms/integration/api/v1/timeseries/AbstractStorageIntegrationTest.java

Jira: https://issues.opennms.org/browse/DC-15

DC-15: External Tag mtype is missing: test also for meta and external tags

---

api/pom.xml
api/src/main/java/org/opennms/integration/api/v1/scv/Credentials.java
api/src/main/java/org/opennms/integration/api/v1/scv/SecureCredentialsVault.java
archetypes/example-kar-plugin/pom.xml
archetypes/pom.xml
common/pom.xml
common/src/main/java/org/opennms/integration/api/v1/scv/immutables/ImmutableCredentials.java
config/pom.xml
karaf-features/pom.xml
pom.xml
sample/pom.xml
test-api/pom.xml
test-suites/pom.xml
test-suites/tss-tests/pom.xml
test-suites/tss-tests/src/main/java/org/opennms/integration/api/v1/timeseries/InMemoryStorage.java

We want to use the SCV in the cloud plugin and thus need to make it available in the integration api.
Jira: https://issues.opennms.org/browse/NMS-14185

NMS-14185: Expose Secure Credentials Vault via Integration API

---

api/src/main/java/org/opennms/integration/api/v1/config/thresholding/Basethresholddef.java
config/src/main/java/org/opennms/integration/api/xml/ClasspathThresholdingConfigLoader.java
config/src/main/java/org/opennms/integration/api/xml/schema/thresholding/Basethresholddef.java
sample/src/test/java/org/opennms/integration/api/sample/MyThresholdingConfigExtensionTest.java

https://issues.opennms.org/browse/OIA-31
It is pair with OpenNMS branch jira/OIA-31.

OIA-31: change Basethresholddef rearm value & trigger to string

---

api/pom.xml
archetypes/example-kar-plugin/pom.xml
archetypes/pom.xml
common/pom.xml
config/pom.xml
karaf-features/pom.xml
pom.xml
sample/pom.xml
test-api/pom.xml
test-suites/pom.xml
test-suites/tss-tests/pom.xml

Change ver. for fix OpenNMS build
https://issues.opennms.org/browse/OIA-31

OIA-31: change ver 0.8.2 > 0.8.3

---

api/pom.xml
api/src/main/java/org/opennms/integration/api/v1/timeseries/Aggregation.java
api/src/main/java/org/opennms/integration/api/v1/timeseries/TimeSeriesStorage.java
archetypes/example-kar-plugin/pom.xml
archetypes/pom.xml
common/pom.xml
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableDataPoint.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableMetric.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableSample.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableTag.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableTagMatcher.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableTimeSeriesData.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/ImmutableTimeSeriesFetchRequest.java
common/src/main/java/org/opennms/integration/api/v1/timeseries/immutables/MetricValidator.java
config/pom.xml
karaf-features/pom.xml
pom.xml
sample/pom.xml
test-api/pom.xml
test-suites/pom.xml
test-suites/tss-tests/pom.xml
test-suites/tss-tests/src/main/java/org/opennms/integration/api/v1/timeseries/InMemoryStorage.java

InMemory storage: implement new method for fetching.
Jira: https://issues.opennms.org/browse/DC-185

DC-185: Make time series objects serializable to store off heap.

---

api/pom.xml
api/src/main/java/org/opennms/integration/api/v1/flows/Flow.java
api/src/main/java/org/opennms/integration/api/v1/flows/FlowException.java
api/src/main/java/org/opennms/integration/api/v1/flows/FlowRepository.java
archetypes/example-kar-plugin/pom.xml
archetypes/pom.xml
common/pom.xml
config/pom.xml
karaf-features/pom.xml
pom.xml
sample/pom.xml
test-api/pom.xml
test-suites/pom.xml
test-suites/tss-tests/pom.xml

Adds a model interface for flows and a plugin interface to persist such flows.

OIA-41: Support flow persistence

---

api/src/main/java/org/opennms/integration/api/v1/model/InMemoryEvent.java
common/src/main/java/org/opennms/integration/api/v1/model/immutables/ImmutableInMemoryEvent.java

* JIRA: https://issues.opennms.org/browse/OIA-48

OIA-48: Allow interface, service and time for OIA events

---

api/src/main/java/org/opennms/integration/api/v1/model/MonitoredService.java
common/src/main/java/org/opennms/integration/api/v1/model/immutables/ImmutableIpInterface.java
common/src/main/java/org/opennms/integration/api/v1/model/immutables/ImmutableMonitoredService.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/OIA-47

OIA-47: Expose MonitoredService Entities

---

api/pom.xml
api/src/main/java/org/opennms/integration/api/v1/scv/SecureCredentialsVault.java
archetypes/example-kar-plugin/pom.xml
archetypes/pom.xml
common/pom.xml
config/pom.xml
karaf-features/pom.xml
pom.xml
sample/pom.xml
test-api/pom.xml
test-suites/pom.xml
test-suites/tss-tests/pom.xml

https://issues.opennms.org/browse/OIA-52

OIA-52: Implement deletion of SCV entries

---

api/pom.xml
api/src/main/java/org/opennms/integration/api/v1/dao/AlarmDao.java
api/src/main/java/org/opennms/integration/api/v1/model/Alarm.java
archetypes/example-kar-plugin/pom.xml
archetypes/pom.xml
common/pom.xml
common/src/main/java/org/opennms/integration/api/v1/model/immutables/ImmutableAlarm.java
config/pom.xml
karaf-features/pom.xml
pom.xml
sample/pom.xml
test-api/pom.xml
test-suites/pom.xml
test-suites/tss-tests/pom.xml

This PR adds support for doing a number of ticketing-related operations to alarms
https://opennms.atlassian.net/browse/NMS-15439

NMS-15439 alarm ticketing improvements

---

.circleci/config.yml
config/pom.xml
pom.xml

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/OIA-57

OIA-57: Upgrade to Java17

---

archetypes/example-kar-plugin/src/main/resources/archetype-resources/assembly/kar/pom.xml
archetypes/example-kar-plugin/src/main/resources/archetype-resources/karaf-features/pom.xml
archetypes/example-kar-plugin/src/main/resources/archetype-resources/pom.xml

* Please [make an issue in the OpenNMS issue tracker](https://opennms.atlassian.net/) if there isn't one already.<br />Once there is an issue, please:
1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
2. update the Jira link at the bottom of this comment to refer to the real issue number
3. prefix your commit messages with the issue number, if possible
4. once you've created this PR, please link to it in a comment in the Jira issue
Don't worry if this sounds like a lot, we can help you get things set up properly.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke tests?**
* If this is a new or updated feature, is there documentation for the new behavior?
* If this is new code, are …

OIA-58: Update archetype config to make it compile with Java 17

---

api/src/main/java/org/opennms/integration/api/v1/model/MonitoredService.java
common/src/main/java/org/opennms/integration/api/v1/model/immutables/ImmutableMonitoredService.java

* Jira (Issue Tracker): https://opennms.atlassian.net/browse/MPLUG-21

MPLUG-21: Add status field on MonitoredService
